<div class="page-container">
<div class="pd-20">
	<div class="text-c">							
	<form class="form-horizontal" method="get" action="/v1/data/chan">
		时间：
			<input value="<?php echo $start_time;?>" placeholder="开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})" name="start_time"/>
			-
			<input value="<?php echo $end_time;?>" placeholder="结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})" name="end_time"/>
			<input type="submit" class="btn btn-primary" value="查看" /> 
		    <a class="btn btn-primary" href="/v1/data/chan?start_time=<?php echo date('Y-m-d');?>&end_time=<?php echo date('Y-m-d');?>" class="btn">今日 </a> 
		    <a class="btn btn-primary" href="/v1/data/chan?start_time=<?php echo date('Y-m-d',strtotime("-6 day"));?>&end_time=<?php echo date('Y-m-d');?>" class="btn">七天</a> 
		    <a class="btn btn-primary" href="/v1/data/chan?start_time=<?php echo date('Y-m-01');?>&end_time=<?php echo date('Y-m-d');?>" class="btn">当月</a> 
		    <a class="btn btn-primary" href="/v1/data/chan?start_time=<?php echo date('Y-m-d',strtotime("-29 day"));?>&end_time=<?php echo date('Y-m-d');?>" class="btn">30天</a>

		    <a class="btn btn-primary" download="渠道.csv" class="btn" onclick="exportToExcel(this,'csv_data')">导出</a>
	</form>
	</div>
	<div class="mt-20">
	<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20" id="csv_data">
		<thead>
			<tr>
				<th>日期</th>
				<th>渠道</th>
				<th width="120">新增用户数</th>
				<th>活跃用户数</th>
				<th>付费用户数</th>
				<th>新增付费人数</th>	
				<th>新增付费金额</th>					
				<th>总付费金额</th>
				<th>总付费率(%)</th>					
				<th>活跃ARPU</th>
				<th>付费ARPU</th>
			</tr>
		</thead>

		<tr>
			<th>总计</th>
			<th>--</th>
			<th><?php echo intval(@$total_new_user);?></th>
			<th><?php echo intval(@$total_active_user);?></th>
			<th><?php echo intval(@$total_pay_user);?></th>
			<th><?php echo intval(@$total_first_pay_user);?></th>
			<th><?php echo number_format(@$total_first_pay_rmb,1);?></th>
			<th><?php echo number_format(@$total_pay_rmb,1);?></th>
			<th><?php echo number_format(@$total_pay_rate,2);?></th>
			<th><?php echo number_format(@$total_active_arpu,1);?></th>
			<th><?php echo number_format(@$total_pay_arpu,1);?></th>
		</tr>

		<?php foreach($chans as $ch):?>
			<?php $c = $ch['chan_id'];?>
			<tr>
				<td width="130px"><?php echo $real_start_time;?></td>
				<td><?php echo @$c;?></td>
				<td><?php echo intval(@$day[$c]['new_user']);?></td>
				<td><?php echo intval(@$day[$c]['active_user']);?></td>
				<td><?php echo intval(@$day[$c]['pay_user']);?></td>
				<td><?php echo intval(@$day[$c]['first_pay_user']);?></td>
				<td><?php echo number_format(@$day[$c]['first_pay_rmb'],1);?></td>
				<td><?php echo number_format(@$day[$c]['pay_rmb'],1);?></td>
				<td><?php echo number_format(@$day[$c]['pay_rate'],1);?></td>
				<td><?php echo number_format(@$day[$c]['active_arpu'],1);?></td>
				<td><?php echo number_format(@$day[$c]['pay_arpu'],1);?></td>								</tr>
		<?php endforeach;?>
	</table>
	</div>
	<div class="pages"><?php echo $pages;?></div>
</div>

