<div class="page-container">
	<form class="form-horizontal" method="get" action="">			
				<div class="mb10">							
				玩家ID： 
					<input type="text" name="uid_list" class="input-text" style="width:600px" value="<?php echo @$uid_list;?>" placeholder="多个玩家ID，英文分号;给开"> 
					<input type="submit"  name='submit' class="btn btn-primary" value="查看" /> 
				</div>			
		</form>

		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>日志ID</th>
					<th>玩家ID</th>
					<th>物品ID</th>
					<th>数量</th>
					<th>余额</th>
					<th>途径</th>
					<th>GUID</th>
					<th>时间</th>
				</tr>
			</thead>				
			<?php foreach($rows as $row){?>
				<tr>
					<td><?php echo $row['id']?></td>
					<td><?php echo $row['uid']?></td>
					<td><?php echo $row['item_id']?></td>
					<td><?php echo $row['item_num']?></td>
					<td><?php echo $row['balance']?></td>
					<td><?php echo $row['way']?></td>
					<td><?php echo $row['guid']?></td>
					<td><?php echo $row['deadline']?></td>				
				</tr>
			<?php }?>

		</table>
		<div class="pages"><?php echo $pages;?></div>
</div>
