<div class="page-container">
<div class="pd-20">
	<div class="text-c">							
	<form class="form-horizontal" method="get" action="/v1/data/item_by_way">			
			物品:
			<select class="input-text" style="width: 150px;" name="item_id"> 
				<?php foreach ( $items as $item ): ?>
				<option value="<?php echo $item[0]; ?>" <?php if ( $item_id == $item[0]): ?> selected <?php endif;?> > <?php echo $item[1]; ?></option>
				<?php endforeach; ?> 
			</select>
			时间：
			<input value="<?php echo $start_time;?>" placeholder="开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})" name="start_time"/>
			-
			<input value="<?php echo $end_time;?>" placeholder="结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})" name="end_time"/>
			
			<input type="submit" class="btn btn-primary" value="查看" /> 
		    <a class="btn btn-primary" href="/v1/data/item_by_way?start_time=<?php echo date('Y-m-d');?>&end_time=<?php echo date('Y-m-d');?>" class="btn">今日 </a> 
		    <a class="btn btn-primary" href="/v1/data/item_by_way?start_time=<?php echo date('Y-m-d',strtotime("-6 day"));?>&end_time=<?php echo date('Y-m-d');?>" class="btn">七天</a> 
		    <a class="btn btn-primary" href="/v1/data/item_by_way?start_time=<?php echo date('Y-m-01');?>&end_time=<?php echo date('Y-m-d');?>" class="btn">当月</a> 
		    <a class="btn btn-primary" href="/v1/data/item_by_way?start_time=<?php echo date('Y-m-d',strtotime("-29 day"));?>&end_time=<?php echo date('Y-m-d');?>" class="btn">30天</a>
		    <a class="btn btn-primary" download="金币系统.csv" class="btn" onclick="exportToExcel(this,'csv_data')">导出</a>
	</form>
	</div>
	<div class="mt-20">
	<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20" id="csv_data">
		<thead>
			<tr>
			<th></th>
			<?php foreach($ways as $way):?>
			<th><?php echo $way;?></th>	
			<?php endforeach;?>
			</tr>
		</thead>
		<?php for($t=$real_end_time;$t>$real_start_time;):?>
			<?php $t=date('Y-m-d',strtotime("$t -1 day"));?>
			<tr>
				<td width="130px"><?php echo $t;?></td>
			<?php foreach($ways as $way):?>
				<td>
				<?php 
					echo intval(@$day["{$t}_product_$way"]);
				?>
			</td>
			<?php endforeach;?>
			</tr>
		<?php endfor;?>
	</table>
	</div>
	<div class="pages"><?php echo $pages;?></div>
</div>

