<div class="page-container">
	<form class="form-horizontal" method="post" action="/v1/data/remain_data">			
			<div class="mb10">
			渠道账号：
			<select class="input-text Wdate" style="width: 150px;" name="chan_id"> 
				<option value="0">全部渠道</option>
				<?php for($i=0; $i<count($channels); $i++){ ?>
				<option value="<?php echo $channels[$i]?>" <?php if($chan_id == $channels[$i]){echo "selected='selected'";}?>><?php echo $channels[$i]?></option>
				<?php } ?> 
			</select>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;										
			时间：
				<input value="<?php echo $start_time?>" placeholder="开始时间..." class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="start_time"/>
				-
				<input value="<?php echo $end_time?>" placeholder="结束时间..." class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="end_time"/>
				
				<input type="submit"  name='submit' class="btn btn-warning" value="搜索" /> 
			    <input type="button"  onclick="exports()" class="btn btn-primary" value="导出exl" />
			</div>			
		</form>
		
		<table class="table table-hover table-bordered table-list mt-20">
					<tr>
						<th style='color:#f00'>*隔天数据*</th>
					</tr>
		</table>

		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>日期</th>
					<th>渠道账号</th>
					<th>注册人数</th>
					<th>二日</th>
					<th>三日</th>
					<th>七日</th>
					<th>十五日</th>
					<th>三十日</th>
					<th>六十日</th>
				</tr>
			</thead>
			<?php foreach($remainMsg as $v){ ?>
				<tr>
				<?php
					if($v['registers']==0 || $v['two_rm']==0){
						$two_rm_per = '0.00';
					}else{			
						$two_rm_per = (round($v['two_rm']/$v['registers'],2))*100;
					}
					if($v['registers']==0 || $v['three_rm']==0){
						$three_rm_per = '0.00';
					}else{
						$three_rm_per = (round($v['three_rm']/$v['registers'],2))*100;
					}
					if($v['registers']==0 || $v['seven_rm']==0){
						$seven_rm_per = '0.00';
					}else{
						$seven_rm_per = (round($v['seven_rm']/$v['registers'],2))*100;
					}
					if($v['registers']==0 || $v['fifteen_rm']==0){
						$fifteen_rm_per = '0.00';
					}else{
						$fifteen_rm_per = (round($v['fifteen_rm']/$v['registers'],2))*100;
					}
					if($v['registers']==0 || $v['thirty_rm']==0){
						$thirty_rm_per = '0.00';
					}else{
						$thirty_rm_per = (round($v['thirty_rm']/$v['registers'],2))*100;
					}
					if($v['registers']==0 || $v['sixty_rm']==0){
						$sixty_rm_per = '0.00';
					}else{
						$sixty_rm_per = (round($v['sixty_rm']/$v['registers'],2))*100;
					}
				?>
					<td width="170px"><?php echo $v['create_time']?></td>
					<td><?php echo $v['chan_id']?></td>
					<td><?php echo $v['registers']?></td>
					<td><?php echo $v['two_rm'].'('.$two_rm_per.'%)'?></td>
					<td><?php echo $v['three_rm'].'('.$three_rm_per.'%)'?></td>
					<td><?php echo $v['seven_rm'].'('.$seven_rm_per.'%)'?></td>
					<td><?php echo $v['fifteen_rm'].'('.$fifteen_rm_per.'%)'?></td>
					<td><?php echo $v['thirty_rm'].'('.$thirty_rm_per.'%)'?></td>
					<td><?php echo $v['sixty_rm'].'('.$sixty_rm_per.'%)'?></td>
				</tr>
			<?php } ?>
		</table>
		<div class="pages"><?php echo $pages;?></div>
</div>

<script type="text/javascript">
	function exports(){
		window.location="/v1/data/remain_data/export";
		}
</script>


