<div class="page-container">
	<form class="form-horizontal" method="get" action="">			
				<div class="mb10">							
				玩家ID： 
					<input type="text" name="uid_list" class="input-text" style="width:600px" value="<?php echo @$uid_list;?>" placeholder="多个玩家ID，英文分号;给开"> 
					<input type="submit"  name='submit' class="btn btn-primary" value="查看" /> 
				</div>			
		</form>

		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>玩家ID</th>
					<th>昵称</th>
					<th>金币</th>
					<th>钻石</th>
					<th>房卡</th>
					<th>对局数</th>
					<th>充值金额</th>
					<th>上级ID</th>
					<th>代理等级</th>
					<th>最近登陆时间</th>
					<th>注册时间</th>
				</tr>
			</thead>				
			<?php foreach($rows as $row){?>
				<tr>
					<td><a href="javascript:void(0)" onclick="Hui_admin_tab(this)" class="maincolor" data-title="玩家" _href="/v1/data/user_info?uid=<?php echo $row['uid'];?>"><?php echo $row['uid'];?></a></td>
					<td><?php echo $row['nickname']?></td>
					<td><?php echo $row['gold']?></td>
					<td><?php echo $row['diamond']?></td>
					<td><?php echo $row['score_card']?></td>
					<td><?php echo $row['play_times']?></td>
					<td><?php echo $row['pay_rmb']?></td>
					<td><?php echo @$row['parent_uid']?></td>				
					<td><?php echo $row['agent_level']?></td>				
					<td><?php echo $row['enter_time']?></td>				
					<td><?php echo $row['create_time']?></td>				
				</tr>
			<?php }?>

		</table>
		<div class="pages"><?php echo $pages;?></div>
</div>
