		<div data-role="content" role="main">
			<form action="" method="post" name="addagmentform">
				<table data-role="table" id="myTable">
					<thead>
						<tr>
							<th data-priority="1"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center"><label><b>填写推广员信息</b></label></td>
						</tr>
						<tr>
							<td style="text-align: center"><label><b>真实姓名:</b></label>
								<input type="text" name="name" id="name" placeholder="真实姓名">
								<p style="text-align: center">一定要与微信真实认证的姓名完全一致<br><label style="color: #8b0000">微信绑定银行卡的真实姓名</label>,否则无法提现到账</p>
							</td>
						</tr>
						<tr>
							<td style="text-align: center"><label><b>游戏ID:</b></label>
								<input type="text" name="uid" id="uid" placeholder="游戏ID">
							</td>
						</tr>
						<tr>
							<td style="text-align: center;border-bottom: 0px;"><label><b>手机号:</b></label>
								<input type="tel" name="phone" id="phone" placeholder="手机号">
							</td>
						</tr>
						<tr>
							<td style="text-align: center">
								<input type="button" id="bc" data-theme="b" value="创建推广员">
							</td>
						</tr>
					</tbody>
				</table>
			</form>
	</div>
	<script>
		$("#bc").click(function () {
			name = $("#name").val();
			phone= $("#phone").val();
			uid = $("#vcode").val();
			if (name == "" || phone == "" || uid == "") {
				msg('输入不完整');
			} else {
				document.addagmentform.submit();
			}

		});

		//校验手机号是否合法
		function checkPhone(phone) {
			return /^1\d{10}$/.test(phone);
		}

		function msg(txt) {
			layer.open({
				content: txt
				, btn: '好的'
			});
		}
		var errmsg = "<?php echo @$errmsg;?>";
		if ( errmsg ) {
			msg(errmsg);
		}
	</script>
	
