	 <div data-role="footer" data-position="fixed">
        <div data-role="navbar">
          <ul>
            <li>
              <a data-theme="c" data-ajax="false" href="/public/marketing/add_children">创建代理</a>
            </li>
            <li>
              <a data-theme="c" data-ajax="false" href="/public/marketing/agent">我的代理</a>
            </li>
          </ul>
        </div>
	  </div>
	  <script>
	  	url = location.pathname;	
		$("[href='"+url+"']").attr("class","ui-bnt-active ui-state-persist");
	  </script>
    </div> <!-- page -->
  </body>
</html>
