<article class="page-container">
	<form action="" method="post" class="form form-horizontal">
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>标题：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<input type="text" class="input-text" value="<?php echo $menu['title'];?>" placeholder="" id="title" name="title">
			</div>
		</div>
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>显示：</label>
			<div class="formControls col-xs-8 col-sm-9 skin-minimal">
				<div class="radio-box">
					<input name="show" type="radio" id="show-1" value="0" <?php if($menu['show'] == 0) echo "checked";?>>
					<label for="show-1">隐藏</label>
				</div>
				<div class="radio-box">
					<input type="radio" id="show-2" name="show" value="1" <?php if($menu['show'] == 1) echo "checked";?>>
					<label for="show-2">可见</label>
				</div>
			</div>
		</div>
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>URI：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<input type="text" class="input-text" value="<?php echo $menu['uri'];?>" placeholder="" id="uri" name="uri">
			</div>
		</div>
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3"><span class="c-red">*</span>父菜单Id：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<select class="input-text" name="parent_id" style="width:20%">
				<option value="-1">新菜单</option>
				<?php foreach ($menus as $m):?>
					<?php if ( $m['parent_id'] == -1 ): ?>
						<option value="<?php echo $m['id'];?>" <?php if ( $m['id'] == $menu['parent_id'] ) echo "selected";?>><?php echo $m['title'];?></option>
					<?php endif; ?>
				<?php endforeach;?>
				</select>
			</div>
		</div>
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3">备注：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<textarea name="coment" cols="" rows="" class="textarea"  placeholder="说点什么...最少输入10个字符" onKeyUp="textarealength(this,100)"><?php echo $menu['coment'];?></textarea>
				<p class="textarea-numberbar"><em class="textarea-length">0</em>/100</p>
			</div>
		</div>
		<div class="row cl">
			<div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
				<input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
			</div>
		</div>
	</form>
</article>
