<div class="page-container">
	<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"> <a href="add_menu" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加菜单</a></span> <span class="r">共有数据：<strong><?php echo count($menu_list);?></strong> 条</span> </div>
	<div class="mt-20">
	<table class="table table-border table-bordered table-hover table-bg table-sort">
		<thead>
			<tr class="text-c">
				<th width="80">菜单Id</th>
				<th width="100">标题</th>
				<th width="40">父菜单Id</th>
				<th width="90">URI</th>
				<th width="150">是否显示</th>
				<th width="150">备注</th>
				<th width="100">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach(array_reverse($menu_list) as $menu): ?>
			<tr class="text-c">
				<td><?php echo $menu['id'];?></td>
				<td><?php echo $menu['title'];?></td>
				<td><?php echo $menu['parent_id'];?></td>
				<td><?php echo $menu['uri'];?></td>
				<td><?php echo $menu['show'];?></td>
				<td><?php echo $menu['coment'];?></td>
				<td class="td-manage"><a title="编辑" href="edit_menu/<?php echo $menu['id'];?>" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a> </td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	</div>
</div>




