<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css">
  <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
  <script src="/asset/share/layer.js"></script>
  <link rel="stylesheet" href="/asset/share/main.css">
  <title>"欢迎使用熊猫麻将代理系统"</title>
</head>

<body>
	<div data-role="page">
    	<div data-role="header" data-theme="b">
		<?php if ($share): ?>
		<a href="/public/share/index" data-icon="home" data-theme="b" data-ajax="false">推广</a>
		<?php endif;?>
            <h2><?php echo $title;?></h2>
		<!--<a href="/share/get_info" data-icon="home" data-theme="b" data-ajax="false">首页</a>-->
		</div>

