<div class="page-container">
	<form class="form-horizontal" method="get" action="">			
		<div class="mb10">							
			玩家ID： 
			<input type="text" name="uid_list" class="input-text" style="width:600px" value="<?php echo @$uid_list;?>" placeholder="多个玩家ID，英文分号;给开"> 
			<input type="submit"  name='submit' class="btn btn-primary" value="查看" /> 
			<a href="add_user" class="btn btn-success">新建</a>
		</div>			
	</form>
		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>序号</th>
					<th>玩家ID</th>
					<th>姓名</th>
					<th>推荐码</th>
					<th>代理等级</th>
					<th>二级人数</th>
					<th>三级人数</th>
					<th>上级代理</th>
					<th>下级充值</th>
					<th>创建时间</th>
					<th>操作</th>
				</tr>
			</thead>				
			<?php foreach($rows as $row):?>
			<tr>
				<td><?php echo $row['id']?></td>
				<td><?php echo $row['uid']?></td>
				<td><?php echo $row['name']?></td>
				<td><?php echo @$row['code']?></td>
				<td><?php echo $levels[$row['level']]?></td>	
				<td><?php echo $row['users_lv2']?></td>		
				<td><?php echo $row['users_lv3']?></td>	
				<td><?php echo @$row['agent_uid']?></td>	
				<td><?php echo $row['pay_lv2']+$row['pay_lv3']?></td>	
				<td><?php echo $row['create_time']?></td>	
				<td class="td-manage"><a title="编辑" href="add_user?uid=<?php echo $row['uid'];?>" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a></td>				
			</tr>
		<?php endforeach;?>

	</table>
	<div class="pages"><?php echo $pages;?></div>
</div>
