        <div
            data-role="content" class="ui-content" role="main">
            <table style="width: 96%;margin-left: 2%; border:1px lightgray;border-collapse: collapse;" class="ui-shadow" id="myTable">
                <thead>
                    <tr>
                        <th colspan="6">我的推广员</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="style1">
                        <td width="10%">序号</td>
                        <td width="20%">游戏ID</td>
                        <td width="20%">昵称</td>
                        <td width="15%">上级</td>
                        <td>时间</td>
                    </tr>

					<?php if (empty($last) == true): ?>
                    <tr><td colspan="6">无记录</td></tr>
					<?php else: ?>
					<?php foreach ($last as $id=>$row): ?>
                    <tr>
						<td><?php echo $id+1 ?></td>
						<td><?php echo $row['uid']; ?></td>
						<td><?php echo $row['nickname']; ?></td>
						<td><?php echo $row['parent_uid']; ?></td>
						<td><?php echo $row['create_time']; ?></td>
                    </tr>
					<?php endforeach;?>
					<?php endif; ?>

                </tbody>
            </table>
		<div>
			<a href="/public/share/get_last_share/<?php echo @$cur_page-1;?>" data-role="button" data-inline="true" data-ajax="false">上一页</a>
			<?php echo @$cur_page."/".@$total_page."页";?>
			<a href="/public/share/get_last_share/<?php echo @$cur_page+1;?>" data-role="button" data-inline="true" data-ajax="false">下一页</a>
		</div>
    </div>

