<div class="page-container">
		<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"> <a href="add_chan" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加渠道</a></span> </div>
		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>序号</th>
					<th>渠道号</th>
					<th>备注</th>
					<th>时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<?php foreach($rows as $row):?>
				<tr>				
					<td><?php echo $row['id']; ?></td>
					<td><?php echo $row['chan_id']; ?></td>
					<td><?php echo $row['coment']; ?></td>
					<td><?php echo $row['create_time']; ?></td>
					<td class="td-manage"><a title="编辑" href="/v1/system/add_chan/<?php echo $row['id'];?>" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont"></i></a> </td>
				</tr>
			<?php endforeach;?>
		</table>
</div>

