<article class="page-container">
	<form action="" method="post" class="form form-horizontal" id="form-member-add">		
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3">配置：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<textarea name="config" cols="" rows="" class="textarea"  placeholder="请输入参数" onKeyUp="textarealength(this,1000)"><?php echo $config;?></textarea>
				<p class="textarea-numberbar"><em class="textarea-length">0</em>/1000</p>
			</div>
		</div>
		<div class="row cl">
			<div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
				<input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
			</div>
		</div>
	</form>
</article>

