<article class="page-container">
	<form action="" method="post" class="form form-horizontal">
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3">庄家连续当庄次数：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<input type="text" class="input-text" value="<?php echo @$config["SimenyazhuDealerTimes"];?>" placeholder="" name="simenyazhu_dealer_times">
			</div>
		</div>
		<div class="row cl">
			<label class="form-label col-xs-4 col-sm-3">系统扣税(0~400)：</label>
			<div class="formControls col-xs-8 col-sm-9">
				<input type="text" class="input-text" value="<?php echo @$config["SimenyazhuSystemTax"];?>" placeholder="0~400" name="simenyazhu_system_tax">
			</div>
		</div>

		<div class="row cl">
			<div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
				<input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;提交&nbsp;&nbsp;">
			</div>
		</div>
	</form>
</article>

