<div class="page-container">
	<div class="cl pd-5 bg-1 bk-gray mt-20">
		<span class="l"> <a href="add_activity" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加活动</a></span>
		<span class="l" style="margin-left:10px;"> <a href="add_actype" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加活动类型</a></span>
		<span class="r">共有数据：<strong><?php echo count($activity_list);?></strong> 条</span>
	</div>
	<div class="mt-20">
	<table class="table table-border table-bordered table-hover table-bg table-sort">
		<thead>
			<tr class="text-c">
				<th width="80">编号</th>
				<th width="100">标题</th>
				<th width="40">活动类型</th>
				<th width="90">开始时间</th>
				<th width="90">结束时间</th>
				<th width="60">排序</th>
				<th width="100">操作</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($activity_list as $v){ ?>			
			<tr class="text-c">				
				<td><?php echo $v['id']?></td>
				<td><?php echo $v['title']?></td>
				<td><?php echo $v['actype']?></td>
				<td><?php echo $v['start_time']?></td>
				<td><?php echo $v['end_time']?></td>
				<td>
					<?php 
						$params = json_decode($v['params'],true);
						if(empty($params['Rank'])){
							echo 0;
						}else{
							echo $params['Rank'];
						}
					?>
				</td>
				<td class="td-manage"><a title="编辑" href="edit_activity/<?php echo $v['id']?>" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a></td>
			</tr>
			<?php }?>
		</tbody>
	</table>
	</div>
</div>




